# Generated by Django 6.0 on 2025-12-22 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_children_count_profile_ethnicity'),
        ('interactions', '0003_block_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips_sent', to='accounts.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips_received', to='accounts.profile')),
            ],
            options={
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
    ]
