# Generated by Django 6.0 on 2025-12-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_city_alter_profile_nationality'),
        ('interactions', '0004_skip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_received', to='accounts.profile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_made', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['viewed', '-created_at'], name='interaction_viewed__e235fc_idx'), models.Index(fields=['viewer', 'viewed'], name='interaction_viewer__1f8583_idx')],
            },
        ),
    ]
