# Generated by Django 6.0 on 2025-12-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_children_status_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('white', 'White / Caucasian'), ('black', 'Black / African / Caribbean'), ('asian_east', 'East Asian'), ('asian_south', 'South Asian'), ('hispanic', 'Hispanic / Latino'), ('middle_eastern', 'Middle Eastern'), ('native', 'Native American / Indigenous'), ('pacific', 'Pacific Islander'), ('mixed', 'Mixed / Multi-racial'), ('other', 'Other')], max_length=30),
        ),
    ]
