# Generated by Django 6.0 on 2025-12-22 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_children_count_profile_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('white', 'White / Caucasian'), ('black', 'Black'), ('Shona', 'Shona'), ('Zimbabwean', 'Zimbabwean'), ('ndebele', 'Ndebele'), ('Zulu', 'Zulu'), ('Xhosa', 'Xhosa'), ('Tswana', 'Tswana'), ('pedi', 'Pedi'), ('tsonga', 'Tsonga'), ('swazi', 'Swazi'), ('venda', 'Venda'), ('colored', 'Colored'), ('indian', 'Indian')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='profile_photos/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.profile')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
