# Generated by Django 6.0 on 2025-12-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_ethnicity_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('', 'Select City'), ('Harare', 'Harare, Zimbabwe'), ('Bulawayo', 'Bulawayo, Zimbabwe'), ('Chitungwiza', 'Chitungwiza, Zimbabwe'), ('Mutare', 'Mutare, Zimbabwe'), ('Gweru', 'Gweru, Zimbabwe'), ('Kwekwe', 'Kwekwe, Zimbabwe'), ('Kadoma', 'Kadoma, Zimbabwe'), ('Masvingo', 'Masvingo, Zimbabwe'), ('Chinhoyi', 'Chinhoyi, Zimbabwe'), ('Victoria Falls', 'Victoria Falls, Zimbabwe'), ('Johannesburg', 'Johannesburg, SA'), ('Cape Town', 'Cape Town, SA'), ('Durban', 'Durban, SA'), ('Pretoria', 'Pretoria, SA'), ('Port Elizabeth', 'Port Elizabeth, SA'), ('Bloemfontein', 'Bloemfontein, SA'), ('Nelspruit', 'Nelspruit, SA'), ('Polokwane', 'Polokwane, SA'), ('Sandton', 'Sandton, SA'), ('Midrand', 'Midrand, SA'), ('Gaborone', 'Gaborone, Botswana'), ('Lusaka', 'Lusaka, Zambia'), ('Lilongwe', 'Lilongwe, Malawi'), ('Windhoek', 'Windhoek, Namibia'), ('London', 'London, UK'), ('Manchester', 'Manchester, UK'), ('Birmingham', 'Birmingham, UK'), ('New York', 'New York, USA'), ('Toronto', 'Toronto, Canada'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('Zimbabwe', 'Zimbabwe'), ('South Africa', 'South Africa'), ('Botswana', 'Botswana'), ('Namibia', 'Namibia'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Other', 'Other')], max_length=100),
        ),
    ]
