# Generated by Django 6.0 on 2026-01-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_city_alter_profile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('', 'Select City'), ('Harare', 'Harare, Zimbabwe'), ('Bulawayo', 'Bulawayo, Zimbabwe'), ('Chitungwiza', 'Chitungwiza, Zimbabwe'), ('Mutare', 'Mutare, Zimbabwe'), ('Gweru', 'Gweru, Zimbabwe'), ('Kwekwe', 'Kwekwe, Zimbabwe'), ('Kadoma', 'Kadoma, Zimbabwe'), ('Masvingo', 'Masvingo, Zimbabwe'), ('Chinhoyi', 'Chinhoyi, Zimbabwe'), ('Victoria Falls', 'Victoria Falls, Zimbabwe'), ('Chegutu', 'Chegutu, Zimbabwe'), ('Johannesburg', 'Johannesburg, South Africa'), ('Cape Town', 'Cape Town, South Africa'), ('Durban', 'Durban, South Africa'), ('Pretoria', 'Pretoria, South Africa'), ('Port Elizabeth', 'Port Elizabeth, South Africa'), ('Bloemfontein', 'Bloemfontein, South Africa'), ('Nelspruit', 'Nelspruit, South Africa'), ('Polokwane', 'Polokwane, South Africa'), ('Sandton', 'Sandton, South Africa'), ('Midrand', 'Midrand, South Africa'), ('Umtata', 'Umtata, South Africa'), ('Nelspruit', 'Nelspruit, South Africa'), ('Tshwane', 'Tshwane, South Africa'), ('EastLondon', 'EastLondon, South Africa'), ('Gaborone', 'Gaborone, Botswana'), ('Francistown', 'Francistown, Botswana'), ('Molepolole', 'Molepolole, Botswana'), ('Lusaka', 'Lusaka, Zambia'), ('Kitwe', 'Kitwe, Zambia'), ('Ndola', 'Ndola, Zambia'), ('Maseru', 'Maseru, Lesotho'), ('Mafikeng', 'Mafikeng, Lesotho'), ('Maseru', 'Maseru, Lesotho'), ('Maseru', 'Maseru, Swaziland'), ('Mafikeng', 'Mafikeng, Swaziland'), ('Maseru', 'Maseru, Swaziland'), ('Maseru', 'Maseru, Malawi'), ('Mafikeng', 'Mafikeng, Malawi'), ('Maseru', 'Maseru, Malawi'), ('Nairobi', 'Nairobi, Kenya'), ('Mombasa', 'Mombasa, Kenya'), ('Maseru', 'Maseru, Kenya'), ('Kampala', 'Kampala, Uganda'), ('Mafikeng', 'Mafikeng, Uganda'), ('Maseru', 'Maseru, Uganda'), ('Dar es Salaam', 'Dar es Salaam, Tanzania'), ('Mafikeng', 'Mafikeng, Tanzania'), ('Maseru', 'Maseru, Tanzania'), ('Bujumbura', 'Bujumbura, Burundi'), ('Mafikeng', 'Mafikeng, Burundi'), ('Maseru', 'Maseru, Burundi'), ('Kigali', 'Kigali, Rwanda'), ('Butare', 'Butare, Rwanda'), ('Gisenyi', 'Gisenyi, Rwanda'), ('Windhoek', 'Windhoek, Namibia'), ('Walvis Bay', 'Walvis Bay, Namibia'), ('Swakopmund', 'Swakopmund, Namibia'), ('Oshakati', 'Oshakati, Namibia'), ('Maputo', 'Maputo, Mozambique'), ('Matola', 'Matola, Mozambique'), ('Beira', 'Beira, Mozambique'), ('Nampula', 'Nampula, Mozambique')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('', 'Select Ethnicity'), ('white', 'White / Caucasian'), ('black', 'Black'), ('colored', 'Colored'), ('indian', 'Indian'), ('asian', 'Asian'), ('Basotho', 'Basotho'), ('Bemba', 'Bemba'), ('Chewa', 'Chewa'), ('Damara', 'Damara'), ('Herero', 'Herero'), ('Hutu', 'Hutu'), ('Kalanga', 'Kalanga'), ('Kavango', 'Kavango'), ('Lomwe', 'Lomwe'), ('Lozi', 'Lozi'), ('Makua', 'Makua'), ('Nama', 'Nama'), ('Ndebele', 'Ndebele'), ('Ovambo', 'Ovambo'), ('Pedi', 'Pedi'), ('Sena', 'Sena'), ('Shangani', 'Shangani'), ('Shona', 'Shona'), ('Sotho', 'Sotho'), ('Swati', 'Swati'), ('Tonga', 'Tonga'), ('Tsonga', 'Tsonga'), ('Tswana', 'Tswana'), ('Tutsi', 'Tutsi'), ('Twa', 'Twa'), ('Venda', 'Venda'), ('Xhosa', 'Xhosa'), ('Zulu', 'Zulu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('Zimbabwe', 'Zimbabwe'), ('South Africa', 'South Africa'), ('Botswana', 'Botswana'), ('Namibia', 'Namibia'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Lesotho', 'Lesotho'), ('Swaziland', 'Swaziland'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Burundi', 'Burundi'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi'), ('Other', 'Other')], max_length=100),
        ),
    ]
