# Generated by Django 6.0 on 2026-01-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_residence_country_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('sports', 'Sports & Fitness'), ('travel', 'Travel & Adventure'), ('music', 'Music & Arts'), ('reading', 'Reading & Writing'), ('gaming', 'Gaming & Technology'), ('movies', 'Movies & TV'), ('cooking', 'Cooking & Food'), ('nature', 'Nature & Outdoors'), ('photography', 'Photography'), ('fashion', 'Fashion')], max_length=50),
        ),
    ]
