# Generated by Django 6.0 on 2025-12-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_thread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
