# Generated by Django 6.0 on 2025-12-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profile_gender_profile_is_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField(default=99)),
                ('interested_in', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('all', 'All')], default='all', max_length=10)),
                ('max_distance', models.IntegerField(default=50, help_text='Maximum distance in km')),
                ('show_me', models.BooleanField(default=True, help_text='Show my profile in discovery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.profile')),
            ],
        ),
    ]
