# Generated by Django 6.0 on 2025-12-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='pref_ethnicity',
            field=models.CharField(choices=[('any', 'Any'), ('white', 'White / Caucasian'), ('black', 'Black / African / Caribbean'), ('asian_east', 'East Asian'), ('asian_south', 'South Asian'), ('hispanic', 'Hispanic / Latino'), ('middle_eastern', 'Middle Eastern'), ('native', 'Native American / Indigenous'), ('pacific', 'Pacific Islander'), ('mixed', 'Mixed / Multi-racial'), ('other', 'Other')], default='any', max_length=30),
        ),
        migrations.AddField(
            model_name='preference',
            name='pref_max_children',
            field=models.IntegerField(blank=True, help_text='Maximum number of children a partner has', null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='pref_nationality',
            field=models.CharField(blank=True, help_text='Preferred nationality', max_length=100),
        ),
        migrations.AlterField(
            model_name='preference',
            name='interested_in',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('all', 'All')], default='all', max_length=10),
        ),
    ]
