# Generated by Django 6.0 on 2025-12-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_preference_pref_ethnicity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='max_distance',
        ),
        migrations.AddField(
            model_name='preference',
            name='pref_city',
            field=models.CharField(blank=True, help_text='Preferred city', max_length=100),
        ),
        migrations.AlterField(
            model_name='preference',
            name='interested_in',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_ethnicity',
            field=models.CharField(choices=[('any', 'Any'), ('white', 'White / Caucasian'), ('black', 'Black'), ('Shona', 'Shona'), ('Zimbabwean', 'Zimbabwean'), ('ndebele', 'Ndebele'), ('Zulu', 'Zulu'), ('Xhosa', 'Xhosa'), ('Tswana', 'Tswana'), ('pedi', 'Pedi'), ('tsonga', 'Tsonga'), ('swazi', 'Swazi'), ('venda', 'Venda'), ('colored', 'Colored'), ('indian', 'Indian')], default='any', max_length=30),
        ),
    ]
