# Generated by Django 6.0 on 2026-01-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_alter_preference_pref_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='pref_city',
            field=models.CharField(blank=True, choices=[('', 'Select City'), ('Harare', 'Harare, Zimbabwe'), ('Bulawayo', 'Bulawayo, Zimbabwe'), ('Chitungwiza', 'Chitungwiza, Zimbabwe'), ('Mutare', 'Mutare, Zimbabwe'), ('Gweru', 'Gweru, Zimbabwe'), ('Kwekwe', 'Kwekwe, Zimbabwe'), ('Kadoma', 'Kadoma, Zimbabwe'), ('Masvingo', 'Masvingo, Zimbabwe'), ('Chinhoyi', 'Chinhoyi, Zimbabwe'), ('Victoria Falls', 'Victoria Falls, Zimbabwe'), ('Chegutu', 'Chegutu, Zimbabwe'), ('Johannesburg', 'Johannesburg, South Africa'), ('Cape Town', 'Cape Town, South Africa'), ('Durban', 'Durban, South Africa'), ('Pretoria', 'Pretoria, South Africa'), ('Port Elizabeth', 'Port Elizabeth, South Africa'), ('Bloemfontein', 'Bloemfontein, South Africa'), ('Nelspruit', 'Nelspruit, South Africa'), ('Polokwane', 'Polokwane, South Africa'), ('Sandton', 'Sandton, South Africa'), ('Midrand', 'Midrand, South Africa'), ('Umtata', 'Umtata, South Africa'), ('Tshwane', 'Tshwane, South Africa'), ('East London', 'East London, South Africa'), ('Gaborone', 'Gaborone, Botswana'), ('Francistown', 'Francistown, Botswana'), ('Molepolole', 'Molepolole, Botswana'), ('Lusaka', 'Lusaka, Zambia'), ('Kitwe', 'Kitwe, Zambia'), ('Ndola', 'Ndola, Zambia'), ('Maseru', 'Maseru, Lesotho'), ('Mafikeng', 'Mafikeng, Lesotho'), ('Maseru', 'Maseru, Lesotho'), ('Maseru', 'Maseru, Swaziland'), ('Mafikeng', 'Mafikeng, Swaziland'), ('Maseru', 'Maseru, Swaziland'), ('Lilongwe', 'Lilongwe, Malawi'), ('Blantyre', 'Blantyre, Malawi'), ('Chikwawa', 'Chikwawa, Malawi'), ('Nairobi', 'Nairobi, Kenya'), ('Mombasa', 'Mombasa, Kenya'), ('Maseru', 'Maseru, Kenya'), ('Kampala', 'Kampala, Uganda'), ('Entebbe', 'Entebbe, Uganda'), ('Jinja', 'Jinja, Uganda'), ('Mbarara', 'Mbarara, Uganda'), ('Gulu', 'Gulu, Uganda'), ('Dar es Salaam', 'Dar es Salaam, Tanzania'), ('Dodoma', 'Dodoma, Tanzania'), ('Mwanza', 'Mwanza, Tanzania'), ('Arusha', 'Arusha, Tanzania'), ('Mbeya', 'Mbeya, Tanzania'), ('Gitega', 'Gitega, Burundi'), ('Bujumbura', 'Bujumbura, Burundi'), ('Ngozi', 'Ngozi, Burundi'), ('Rumonge', 'Rumonge, Burundi'), ('Kigali', 'Kigali, Rwanda'), ('Butare', 'Butare, Rwanda'), ('Gisenyi', 'Gisenyi, Rwanda'), ('Windhoek', 'Windhoek, Namibia'), ('Walvis Bay', 'Walvis Bay, Namibia'), ('Swakopmund', 'Swakopmund, Namibia'), ('Oshakati', 'Oshakati, Namibia'), ('Maputo', 'Maputo, Mozambique'), ('Matola', 'Matola, Mozambique'), ('Beira', 'Beira, Mozambique'), ('Nampula', 'Nampula, Mozambique'), ('Tete', 'Tete, Mozambique')], help_text='Preferred city', max_length=100),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pref_nationality',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('Zimbabwe', 'Zimbabwe'), ('South Africa', 'South Africa'), ('Botswana', 'Botswana'), ('Namibia', 'Namibia'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Lesotho', 'Lesotho'), ('Swaziland', 'Swaziland'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Burundi', 'Burundi'), ('Rwanda', 'Rwanda'), ('Other', 'Other')], help_text='Preferred nationality', max_length=100),
        ),
    ]
