# Generated by Django 6.0 on 2026-01-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_alter_preference_pref_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='pref_ethnicity',
            field=models.CharField(choices=[('any', 'Any'), ('white', 'White / Caucasian'), ('black', 'Black'), ('colored', 'Colored'), ('indian', 'Indian'), ('asian', 'Asian'), ('Baganda', 'Baganda'), ('Bakiga', 'Bakiga'), ('Banyankole', 'Banyankole'), ('Basoga', 'Basoga'), ('Basotho', 'Basotho'), ('Bemba', 'Bemba'), ('Chagga', 'Chagga'), ('Chewa', 'Chewa'), ('Chichewa', 'Chichewa'), ('Damara', 'Damara'), ('Ha', 'Ha'), ('Haya', 'Haya'), ('Herero', 'Herero'), ('Hutu', 'Hutu'), ('Iteso', 'Iteso'), ('Kalanga', 'Kalanga'), ('Kavango', 'Kavango'), ('Kikuyu', 'Kikuyu'), ('Lomwe', 'Lomwe'), ('Lozi', 'Lozi'), ('Luhya', 'Luhya'), ('Makua', 'Makua'), ('Nama', 'Nama'), ('Ndebele', 'Ndebele'), ('Ngoni', 'Ngoni'), ('Nyamwezi', 'Nyamwezi'), ('Ovambo', 'Ovambo'), ('Pedi', 'Pedi'), ('Sena', 'Sena'), ('Shangani', 'Shangani'), ('Shona', 'Shona'), ('Sotho', 'Sotho'), ('Sukuma', 'Sukuma'), ('Swati', 'Swati'), ('Tonga', 'Tonga'), ('Tsonga', 'Tsonga'), ('Tswana', 'Tswana'), ('Tutsi', 'Tutsi'), ('Twa', 'Twa'), ('Venda', 'Venda'), ('Xhosa', 'Xhosa'), ('Zulu', 'Zulu')], default='any', max_length=100),
        ),
    ]
